name: .NET Core Desktop

on:
  push:
    branches: 
      [ "master", "main" ]
  pull_request:
    branches: 
      [ "master", "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    env:
      Solution_Name: FacialRecognition.sln                         
      Wap_Project_Directory: FaceRecognitionPackage
      Wap_Project_Path: FaceRecognitionPackage/FaceRecognitionPackage.wapproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish the app to .exe
      run: |
        msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:PublishSingleFile=true /t:Publish
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Upload .exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: |
          FaceRecognitionPackage/bin/${{ matrix.configuration }}/netcoreapp3.1/win-x64/publish/FaceRecognitionPackage.exe
